// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfgnycearkhtpnvghprz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mZ255Y2VhcmtodHBudmdocHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDA1MDAsImV4cCI6MjA2NTU3NjUwMH0.d7ESIL7atW9cPfH7ohzShgHmKDIf-VNN0Sbcrt38skE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);